services:
  fetcher:
    build:
      context: ./server
      dockerfile: fetcher/Dockerfile
    container_name: volatility-cmma-go-fetcher
    volumes:
      - ./server/data:/app/data
      - ./server/logs:/app/logs
    env_file:
      - ./.env
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

  api:
    build:
      context: ./server
      dockerfile: api/Dockerfile
    container_name: volatility-cmma-go-api
    depends_on:
      - fetcher
    volumes:
      - ./server/data:/app/data:ro
    env_file:
      - ./.env
    environment:
      - OHLCV_HISTORY_LIMIT=${OHLCV_HISTORY_LIMIT}
      - DB_PATH=/app/data/cmma.db
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

  nginx:
    build:
      context: ./server/nginx
      dockerfile: Dockerfile
    image: docker.io/library/nginx:latest
    container_name: volatility-cmma-go-nginx
    depends_on:
      - api
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

  volatility-ncmma-notifier:
    build:
      context: ./client/ncmma
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - nginx
    volumes:
      - ./client/ncmma/logs:/app/logs
      - ./client/ncmma/cache:/app/cache
      - ./client/ncmma/data:/app/data
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
